### ISSUE TITLE
Confirmation Form Page

### ISSUE THREAD

**Issue by Robsonsjre** [MainframeHQ/lendo#3]
- confirmation of Forms Data
<img width="586" alt="Screen Shot 2019-06-05 at 2 42 50 PM" src="https://user-images.githubusercontent.com/1886249/58977580-6d503180-87a0-11e9-89ba-290403c4f2ad.png">

**Comment by ggviana** [comment]
Resolved @ https://github.com/MainframeHQ/lendo/pull/26
